export const LIST_GAME = "LIST/GAME"
export const DETAIL_GAME = "DETAIL/GAME"
export const ADD_GAME = "ADD/GAME"
export const ADD_WISHLIST = "ADD/WISHLIST"
export const IS_LOADING = "IS/LOADING"
export const IS_ERROR = "IS/ERROR"